---
title: "Quick Guide - Installation"
author: "Jared M. Ragland"
date: '2023-01-06'
output: html_document
---

# Getting set up quickly with DIMSpec

If your needs require only the database itself and not the attached toolkit, the SQLite file may be downloaded directly from the (NIST Public Data Repository)[TODO LINK] and, along with the provided user guide describing its schema, used by any platform able to interact with SQLite databases.

To get the most from DIMSpec, the software toolkit provided with the project enables a wide variety of customized functionality including convenience, utility, and visualization functions written in the R language, an Application Programming Interface powered by `plumber`, web applications powered by R Shiny, and an integration of the python interface to `rdkit`. A file is provided to control most aspects of the project at `/config/env_glob.txt` which enables setting of the database title, database file name, and a few other settings to customize its configuration. Due to its level of customizibility the DIMSpec project is not distributed as an R package.

The best way to get started with DIMSpec is by cloning the project repository from (GitHub)[TODO LINK] and running the script at `/R/compliance.R`. This should in most cases establish the computational environment supporting the toolkit. When starting from scratch this may take a while as packages are downloaded and installed.

# Requirements

The DIMSpec project is built around R version 4.1 and later and leverages a large number of packages to run as designed. A development environment such as RStudio^1 is highly recommended but is not required. For integration of chemometrics, which is required for several aspects but is not a strict requirement, a python environment including (`reticulate`)[TODO LINK] and (`rdkit`)[TODO LINK] is required. This can be relaxed for those preferring to use an R chemometrics package and if informatics is requested in the environment file but rdkit is not, ChemMineR will be installed; note that ChemMineR functions are not integrated into the project at this time.

^1 [TODO NIST disclaimer statement re commercial product endorsement.]

# Step by Step

# Troubleshooting

## Environments

While the provided convenience script for environment establishment (located at `/R/compliance.R`) should in most cases establish the proper environment for you, it is admittedly using a large number of packages. To increase flexibility across various computing systems and operating systems, a resolved environment (e.g. a renvlock environment) is not provided. The most common place where difficulties may be encountered is package versions and setting up the python environment providing `rdkit` integration.

## Speed Concerns

The full DIMSpec project can take a while to load at first. To speed this up, it is recommended that the compliance script be sourced prior to engaging in any development work with DIMSpec. 
