---
title: "Field Spectral Upload"
author: "bjp"
date: "9/8/2021"
output: pdf_document
---

```{r setup, tidy=TRUE, message=FALSE}
exclusions <- c(".RDS","compliance","create_method_list","generate_db","metadata_xml")
sources <- list.files('src', pattern = ".R$", full.names = TRUE, recursive = TRUE)
sources <- sources[-grep(exclusions, sources)]
invisible(sapply(sources, source))
compoundtable <- read.csv('src/gather/pfas_cmpds.csv', header = TRUE, row.names = NULL)
```

**Note**: JSON has been updated with new format.

## Exporting all files generated by Barzen-Hanson et al.

Set up the directory

```{r dir, tidy=TRUE}
file_dir <- "input/FIELDupload"
all_jsonfile <- list.files(file_dir, ".JSON", full.names = TRUE)
all_methodjson <- lapply(all_jsonfile, parse_methodjson)
all_mzml <- sapply(1:length(all_jsonfile), function(x) paste(dirname(all_jsonfile[x]), "/", all_methodjson[[x]]$sample$name, sep = ""))
```

## Extract data and copy into JSON

```{r gather, tidy=TRUE}
for (i in 1:length(all_jsonfile)) {
  methodjson <- all_methodjson[[i]]
  mzml <- mzMLtoR(all_mzml[[i]])
  dat <- peak_gather_json(methodjson, mzml, compoundtable)
  for (j in 1:length(dat)) {
    qc <- gather_qc(dat[[j]], exactmasses, ms1range = c(0.5, 3), ms1isomatchlimit = 0.5, minerror = 0.01) #minerror is larger for the QTOF data
    output <- dat[[j]]
    output$qc <- qc
    write_json(output, paste("output/FIELD_MS/", gsub("\\.", "_", dat[[j]]$sample$name), "_cmpd", dat[[j]]$compounddata$ID, ".JSON", sep = ""), auto_unbox = TRUE, pretty = TRUE)
  }
}
print("DONE")
```