DROP TABLE IF EXISTS test;
DROP TABLE IF EXISTS norm_col1;
DROP TABLE IF EXISTS norm_col2;
DROP TABLE IF EXISTS norm_col3;
CREATE TABLE IF NOT EXISTS norm_col1 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS norm_col2 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS norm_col3 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS test (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  col1 INTEGER REFERENCES norm_col1(id),
  col2 INTEGER REFERENCES norm_col2(id),
  col3 INTEGER REFERENCES norm_col3(id)
);
                   